#!/bin/sh
set -x
#./fbt --with-updater updater_package copro_dist DIST_SUFFIX=$(git describe --tags)_txs "$@" # flash_usb
./fbt COMPACT=1 DEBUG=0 updater_package DIST_SUFFIX=$(git describe --tags)_txs "$@"
echo consider ./fbt --with-udpater flash_usb
